
apiVersion: v1
kind: Pod
metadata:
  name: init-demo-1
  labels:
    app: web

spec:
  initContainers:
    - name: init-container-demo-1
      image: ubuntu
      command: ["echo","This is an ubuntu image."]
    
    - name: init-busybox
      image: busybox
      command: ["echo","This is an busybox image."]

  containers:
    - name: container-demo-2
      image: redis:latest
    


   






